version: "3.9"
   
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    restart: always
    container_name: redis

  web:
    build: .
    command: python stock/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/stock
    ports:
      - "8000:8000"
    depends_on:
      - db
