version: "3.9"
   
services:
  web:
    image: stock:prod
    container_name: stock
    network_mode: "host"
    volumes:
      - ./:/stock
    command: 
      - /bin/bash
      - -c
      - |
        cd stock
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: "host"

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    network_mode: "host"
    
