# Generated by Django 3.1.4 on 2021-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('open', models.IntegerField()),
                ('close', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BuyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('share', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('log', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
