# Generated by Django 3.1.4 on 2021-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('share', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('log', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aapl',
            name='high',
            field=models.IntegerField(),
        ),
    ]
